spring.application.name=finance
# ===============================
# DATABASE CONFIG (SUPABASE)
# ===============================
spring.datasource.url=jdbc:postgresql://db.chuhrzciezkvhetikydy.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=SaiVenkataSandeep

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.initialization-fail-timeout=0

# use 'update' for dev, 'validate' for prod
spring.jpa.hibernate.ddl-auto=update  

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# CONNECTION POOL (Hikari)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000


# ===============================
# SERVER PORT (optional)
# ===============================
server.port=${PORT:8080}